### PR TITLE
Update the workflow Breakage.yml

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by tmigot** [comment]
@amontoison did you used the files from JSOBestieTemplate ?

**Comment by amontoison** [comment]
Yes, sorry I just found that the PR #306 was opened...

**Comment by tmigot** [comment]
It wasn't updated with the last version, so this PR is better :)

**Comment by tmigot** [comment]
Oh, but can you remove CommentPR.yml and add copier-answers.jso.yml ?

**Comment by amontoison** [comment]
Done :+1:

**Pull request merged**
