### PR TITLE
Use generic sparsity detector

### LINKED ISSUE #232: Bug with upgrade to SymbolicUtils release 1.6 and 1.7
Hi there; recent problem when calling `Ipopt` on an `ADNLModel`, which is what we do in [OptimalControl.jl](https://control-toolbox.org/docs/optimalcontrol/stable). Was working fine until last week, I would say (first ran into the problem one day ago). Attached is a snapshot of the error, seemingly connected to the sparsity pattern analysis of the Hessian by means of `Symbolics.jl` (and `SymbolicUtils`). The problem can be reproduced by running the basic example from `OptimalControl.jl` [here](https://control-toolbox.org).

IMG_3135
IMG_3136

### PR DESCRIPTION
**Pull request by gdalle**
ADTypes.jl v1.0 introduced an abstract [sparse autodiff interface](https://sciml.github.io/ADTypes.jl/stable/#Sparse-AD) for sparsity pattern detection and matrix coloring, which can be implemented by various packages. The latest release of Symbolics.jl, namely [v5.29](https://github.com/JuliaSymbolics/Symbolics.jl/releases/tag/v5.29.0), includes a `SymbolicsSparsityDetector` object which satisfies the ADTypes.jl requirements of sparsity pattern detection.

My PR changes your sparsity detection routines to use this detector object, in order to make it easier to switch later on. For instance, you may want to use `TracerSparsityDetector` from SparseConnectivityTracer.jl instead (see #229 and #230).
The only caveat is that it uses a random vector of Lagrange multiplier, but I think that's correct since the probability of accidental cancellation between constraints is basically zero?

I also removed the compat tweak on SymbolicUtils.jl in the test environment, since it has released a v2.0 which apparently fixes #232.

Ping @amontoison

### CODE REVIEW

**Comment by amontoison** [comment]
Thanks @gdalle!
Can I finalize the PR for SCT.jl after this one?

**Comment by gdalle** [comment]
Sure, it will be even easier to finalize then, just switch the detector object.
The only thing you have to do is figure out if you want to pass this detector all the way down the call chain, e.g. by making it part of one of your structures.

**Comment by gdalle** [comment]
I suspect your failures are partly due to the ungodly way in which you handle Symbolics. It's not in your Project.toml but it's still a dependency somehow. How does that work?

**Comment by gdalle** [comment]
Oops, for `SymbolicsSparsityDetector` to exist I need the latest version of Symbolics, but they have dropped support for 1.6 a long time ago. If you check the [CI log on main](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/actions/runs/9224320585/job/25379348564), you'll see that you're using an old version of Symbolics.
Note that SparseConnectivityTracer.jl supports Julia 1.6 ;)

**Comment by amontoison** [comment]
I propose to update the compat entry of Julia to v1.9 such we have support for package extensions.
The next release will be breaking in all cases because SCT.jl will be the default.

**Comment by gdalle** [comment]
In that case it probably doesn't make much sense to try hard to support Symbolics again. Maybe you can just rebase your SCT PR on this one, switch the detector and we drop Symbolics once and for all?

**Comment by amontoison** [comment]
> In that case it probably doesn't make much sense to try hard to support Symbolics again. Maybe you can just rebase your SCT PR on this one, switch the detector and we drop Symbolics once and for all?

Yes, let's do that.

**Comment by gdalle** [comment]
Closing in favor of #230

**Pull request closed without merging**
