### PR TITLE
Add reverse-forward hprod

### PR DESCRIPTION
**Pull request by tmigot**
only for objective function hprod

### CODE REVIEW

**Comment by tmigot** [comment]
Connected to #165 

When it works, the results are promising https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/benchmark/benchmark/2023-07-07_adnlpmodels_benchmark_hprod_optimized_nscal_1000_mono.png

For instance, the following fails:
```
nlp = OptimizationProblems.ADNLPProblems.clnlbeam(n = 1000, hprod_backend = ADNLPModels.ReverseDiffADHvprod);
n = nlp.meta.nvar
v = [sin(T(i) / 10) for i=1:n]
hprod(nlp, get_x0(nlp), v)
```

**Comment by tmigot** [comment]
@jbcaillau @ocots @amontoison @BaptisteCbl

I added the hprod for the Lagrangian Hessian and optimized sparse hessian. 
This is a clear improvement, see the benchmarks:
- https://github.com/ocots/JumpVSADNLP/pull/2 (note that there was some recent change in the API as well)
- https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/benchmark/benchmark/2023-07-17_adnlpmodels_benchmark_hess_nscal_1000_mono.png
- https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/benchmark/benchmark/2023-07-17_adnlpmodels_benchmark_hprod_lag_optimized_nscal_1000_mono.png

**Review by amontoison — APPROVED** [review]
Fantastic Tangi! 🎉

**Comment by ocots** [comment]
Test with this file: https://github.com/ocots/JumpVSADNLP/blob/master/bench.jl

```R
Hessian of Lagrangian
ADNLP
  1.191 ms (157 allocations: 141.55 KiB)
JuMP
  60.402 μs (137 allocations: 24.08 KiB)
Jacobian of constraints
ADNLP
  10.509 μs (22 allocations: 20.70 KiB)
JuMP
  13.329 μs (15 allocations: 19.80 KiB)
```

Seems to rock!

**Comment by ocots** [comment]
Great job!

New release please 🙏🙏🙏

**Comment by tmigot** [comment]
Let me add some documentation on the new features and improvements, and then the new release (likely tomorrow).

**Comment by jbcaillau** [comment]
Many thanks @tmigot for the timely update. Doing some more tests with @PierreMartinon (Goddard test case).

**Comment by dpo** [comment]
Amazing results @tmigot! Congratulations!

**Comment by jbcaillau** [comment]
@tmigot @amontoison check [this](https://github.com/control-toolbox/CTDirect.jl/issues/61)

**Comment by amontoison** [comment]
Thanks @jbcaillau! Our computation of the sparse Hessian is 20x / 30x slower than JuMP.
We should be able to improve it by taking into account the symmetry of the Hessian to limit the number of directional derivatives of the gradient.

**Comment by jbcaillau** [comment]
@amontoison thanks for the feedback. probably some profiling to do on our side as our objective and constraints evaluations might be far from being efficiently evaluable compared to the pure Julia / JuMP code written for the comparison. 

ps. greetings from JuliaCon2023 with @ocots @jgergaud ... and @tmigot !

**Pull request merged**
