### PR TITLE
pre-allocate result of direction derivative in sparse matrix comp

### PR DESCRIPTION
**Pull request by tmigot**

### CODE REVIEW

**Comment by ocots** [comment]
Here is a bench with a comparison with JuMP: https://github.com/ocots/JumpVSADNLP/

**Comment by ocots** [comment]
With `ADNLPModels` v0.6.2 we get:

```bash
julia> include("bench.jl")
Hessian of Lagrangian
ADNLP
  49.336 ms (337613 allocations: 78.45 MiB)
JuMP
  66.160 μs (137 allocations: 24.08 KiB)
Jacobian of constraints
ADNLP
  48.340 μs (694 allocations: 64.34 KiB)
JuMP
  15.804 μs (15 allocations: 19.80 KiB)
```

**Comment by tmigot** [comment]
Thanks @ocots for the benchmark. Have you tried the branch main or this branch?

**Comment by ocots** [comment]
Not yet.

**Comment by ocots** [comment]
Under the branch `improve-sparse`:

```bash
julia> include("bench.jl")
Hessian of Lagrangian
ADNLP
  31.928 ms (337678 allocations: 78.45 MiB)
JuMP
  59.776 μs (137 allocations: 24.08 KiB)
Jacobian of constraints
ADNLP
  149.469 μs (3382 allocations: 140.11 KiB)
JuMP
  13.549 μs (15 allocations: 19.80 KiB)
```

**Comment by tmigot** [comment]
Argh... I tried to do without SparseDiffTools by default because it makes ADNLPModels dependent on too many packages, but it didn't really improve the jacobian/hessian.

**Comment by tmigot** [comment]
new results in #165 were convincing so I merge it.

**Pull request merged**
