### PR TITLE
benchmarks using up to date setup

### PR DESCRIPTION
**Pull request by MonssafToukal**
This PR is based on @tmigot 's PR. It contains all the necessary files for the benchmaking process.

### CODE REVIEW

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
We need to add the `push_benchmarks.sh` script to master for the benchmarks to work. I didn't take that into account. The file can be found [right here](https://github.com/ProofOfConceptForJuliSmoothOptimizers/BenchmarkSetup/blob/master/push_benchmarks.sh).

**Comment by dpo** [comment]
@MonssafToukal Please open a PR to add it.

**Comment by MonssafToukal** [comment]
> 
> 
> @MonssafToukal Please open a PR to add it.

[Here it is!](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/28)

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Comment by MonssafToukal** [comment]
@JSOBot runbenchmarks

**Pull request closed without merging**
